// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9BepaLAcgpzG6kqGl8uht2zd9pTDzOs',
    appId: '1:513196921710:web:a86427231d26a313b0a77f',
    messagingSenderId: '513196921710',
    projectId: 'populationcharts',
    authDomain: 'populationcharts.firebaseapp.com',
    storageBucket: 'populationcharts.firebasestorage.app',
    measurementId: 'G-0Y6BPWMDXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMpYY6WLBC7k-Eh2z9ZS8ieJ9VFRmfcA',
    appId: '1:513196921710:android:852b803f099e7104b0a77f',
    messagingSenderId: '513196921710',
    projectId: 'populationcharts',
    storageBucket: 'populationcharts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-bdcMFPS7gCGyyQ-mYcLeHaRTBXn81U',
    appId: '1:513196921710:ios:58fc7f64a836f48eb0a77f',
    messagingSenderId: '513196921710',
    projectId: 'populationcharts',
    storageBucket: 'populationcharts.firebasestorage.app',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN-bdcMFPS7gCGyyQ-mYcLeHaRTBXn81U',
    appId: '1:513196921710:ios:58fc7f64a836f48eb0a77f',
    messagingSenderId: '513196921710',
    projectId: 'populationcharts',
    storageBucket: 'populationcharts.firebasestorage.app',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw9BepaLAcgpzG6kqGl8uht2zd9pTDzOs',
    appId: '1:513196921710:web:76df6ff9371b1c95b0a77f',
    messagingSenderId: '513196921710',
    projectId: 'populationcharts',
    authDomain: 'populationcharts.firebaseapp.com',
    storageBucket: 'populationcharts.firebasestorage.app',
    measurementId: 'G-R57Z6P9B65',
  );
}
